export const ADD_COLOR = 'ADD_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const UPDATE_SELECTED_COLOR = 'UPDATE_SELECTED_COLOR';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_IS_SUMMABLE = 'UPDATE_IS_SUMMABLE';
export const UPDATE_IS_REDUCIBLE = 'UPDATE_IS_REDUCIBLE';
export const UPDATE_COLORS_SELECTED_QUANTITY = 'UPDATE_COLORS_SELECTED_QUANTITY';
export const UPDATE_COLOR_QUANTITIES = 'UPDATE_COLOR_QUANTITIES';
export const UPDATE_ACTIVATED_COLORS = 'UPDATE_ACTIVATED_COLORS';
export const UPDATE_CUSTOM = 'UPDATE_CUSTOM';


export const UPDATE_PARTS_SELECTED_QUANTITY = 'UPDATE_PARTS_SELECTED_QUANTITY';
export const UPDATE_PARTS_QUANTITIES = 'UPDATE_PARTS_QUANTITIES';
export const UPDATE_PARTS_IS_SUMMABLE = 'UPDATE_PARTS_IS_SUMMABLE';
export const UPDATE_PARTS_IS_REDUCIBLE = 'UPDATE_PARTS_IS_REDUCIBLE';
export const ADD_PART = 'ADD_PART';
export const REMOVE_PART = 'REMOVE_PART';


export const UPDATE_SELECTED_FORMAT = 'UPDATE_SELECTED_FORMAT';
export const UPDATE_SELECTED_SUBFORMAT = 'UPDATE_SELECTED_SUBFORMAT';
export const UPDATE_FORMAT_QUANTITIES = 'UPDATE_FORMAT_QUANTITIES';
export const CHANGE_DIMENSIONS = 'CHANGE_DIMENSIONS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';



 